IF OBJECT_ID('Songs', 'U') IS NULL
BEGIN

CREATE TABLE Songs (
    Id INT PRIMARY KEY IDENTITY(1,1),
    Guid UNIQUEIDENTIFIER NOT NULL UNIQUE ROWGUIDCOL,
    Name NVARCHAR(256) NOT NULL,
    Contents VARBINARY(MAX) FILESTREAM NOT NULL,
    MimeType VARCHAR(50) NOT NULL
)

END
